version: '3.2'
services:
   #logstash
  s-logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.8.1
    container_name: c-logstash-jdbc-withoutId
    volumes:
      - ./service/elk/logstash/jdbc/MongoDbJdbcDriver:/etc/logstash/jdbc/MongoDbJdbcDriver
      - ./service/elk/logstash/conf:/etc/logstash/conf.d
    command: bin/logstash -f /etc/logstash/conf.d/3-3.jdbc_withoutId.conf
    networks:
      - portal_network
networks:
  portal_network: