version: '3.2'
services:
  #ES
  s-es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1
    container_name: c-es
    volumes:
      - ./service/elk/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/es:/usr/share/elasticsearch/data
      - ./logs/es:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - portal_network
  # mongo
  s-mongodb:
    image: mongo:4.2.3-bionic
    container_name: c-mongodb
    volumes:
      - ./service/mongodb/scripts:/scripts
      - ./data/mongodb:/data/db
      - ./logs/mongodb:/var/log/mongodb
    working_dir: /scripts
    command: /scripts/mongo-run.sh
    environment:
      MONGO_REPLICA_SET_NAME: rs0
      MONGO_REPLICAS: s-mongodb:27017
      MONGO_REPLICA_SET_MEMBERS: "[{'_id':0,'host':'s-mongodb:27017','priority':1}]"
      MONGO_USER_ROOT_NAME: admin
      MONGO_USER_ROOT_PASSWORD: admin
      MONGO_USER_APP_NAME: tedkim
      MONGO_USER_APP_PASSWORD: tedkim
      MONGO_DB_NAME: mydb
      MONGO_BIND_IP: "0.0.0.0"

    ports:
      - "27017:27017"
    networks:
      - portal_network
  #kibana
  s-kibana:
    image:  docker.elastic.co/kibana/kibana-oss:7.8.1
    container_name: c-kibana  
    ports:
      - "5601:5601"
    volumes:
      - ./service/elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./logs/kibana:/usr/share/kibana/logs
    networks:
      - portal_network
networks:
  portal_network:
    